version: '3'
services:
  idbac-kb-dash:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: idbac-kb-dash
    volumes:
      - ./logs:/app/logs:rw
      - ./database:/app/database:ro
      - ./workflows:/app/workflows:ro
      - ./assets:/app/assets:ro
    ports:
    - "5392:5000"
    networks:
      - default
      - nginx-net
    restart: unless-stopped
    command: /app/run_server.sh
    environment:
      VIRTUAL_HOST: idbac.org
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: idbac.org
      LETSENCRYPT_EMAIL: mwang87@gmail.com
    logging:
      options:
        max-size: 50m

  idbac-kb-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: idbac-kb-worker
    volumes:
      - ./logs:/app/logs:rw
      - ./database:/app/database:rw
      - ./workflows:/app/workflows:rw
      - ./assets:/app/assets:rw
    command: /app/run_worker.sh
    restart: unless-stopped
    depends_on: 
      - idbac-kb-redis
      - idbac-kb-rabbitmq
    networks:
      - default
      - nginx-net
    logging:
      options:
        max-size: 50m

  idbac-kb-depositionworker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: idbac-kb-depositionworker
    volumes:
      - ./logs:/app/logs:rw
      - ./database:/app/database:rw
      - ./workflows:/app/workflows:rw
    command: /app/run_depositionworker.sh
    restart: unless-stopped
    depends_on: 
      - idbac-kb-redis
      - idbac-kb-rabbitmq
    networks:
      - default
      - nginx-net
    deploy:
      resources:
        limits:
          memory: 25g
    logging:
      options:
        max-size: 50m

  idbac-kb-rabbitmq:
    container_name: idbac-kb-rabbitmq
    image: rabbitmq
    restart: unless-stopped
    networks:
      - default

  idbac-kb-redis:
    container_name: idbac-kb-redis
    image: valkey/valkey:alpine3.20
    restart: unless-stopped
    networks:
      - default
    logging:
      options:
        max-size: 50m


networks:
  nginx-net:
    external:
      name: nginx-net